language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  chrome: stable
  firefox: latest
  sauce_connect: true
cache:
  directories:
  - bower_components
  - node_modules
before_script:
- npm install -g polymer-cli
- polymer install
script:
- polymer lint
- xvfb-run polymer test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: FK8S6xcmZtglL+Uza8Ez8XNIaoq/0Dv5ZW8SdJ0KKm5QWE6JNZJliWT2D7p1/B3+7OBCQu7LEYi8QwIReCym+bW91eYMyWEN6rZ1e24PiKEU3D//JlAMdujRxcFXsXH+zk4AIBFxMP3HCulSKpP2xOLVtTD0K22Ttg2l23L7mY95/NvIahp0S12DGLh+3PWuqfOp9rrZ0GsDYpDzJoizMNYdiWIgf9962gjO0P0+E5cGNBrM/+MXZCWfMDY6K+vpN8rZJjG8MMNvNC5tQpANZUi57khXYlnSd5/867qThkGp7tiGwqpS9PZ4lvJc0iX+Sdj9sWoTXIGTURQ1ZA1p74RVyU3uCCcdQwsiUXLaN9lqU00TBGvRK2FmbQ/3D6i352QRkzbOMgcgc+Q0Gam4Al50dlA+bcDfwM2PVihL1f64FRXq/47SGoIxcGfTNMyo1R4SgAY90uzywIDxTyat38yw2VwxPQMR/78vn01hSRc4KIuJJlr2khtym0Sf2QisXBj5Zt/RIjSjAvZFbBoPpUwDWHS2hyAQtYBBAMkAwvcVIyWov0xzY+bSc/spejOJJgnIZv5IYxsNBTFMEqMYkoH8YZc07tnZ0YYXGNYejxl2vXzyp8EDjhUnghmtzVJbDBw1Fbyq2yilua8WuUW/janUWtcPRWmsarr1nvNHJaQ=
  - secure: F6RtcEO12kYTCNCXX1DtZkCbcB7nc9yadLqiGJk1Lj9GWIa18ryoldDXXcK0fAoLrIiNL2k8HNp+s6h4+42iTlfVuBoMae1Ebj6a2TrVuL1V+6Qdfs5a6Q5vkVWqTwrMqf+C2Y6XB2rp11BLXqRjhdnaGUjeQRspraR2OavU+o/QMpWa/VoJDw4KptaIVt/qR49ErZTYcBtFv8bfP6m6FqvC06wtvkwivhoCqkw2XrxAczBp9laspW5IJM871AHIIIV5jl8Bezxl5/Ps3chVxeKCSL5cujHfJB0rk3BvxWMFndGFsuDbHoHO8+IDHQlZdjZxZaSR2cY+AK9efJzzBnRfleCDRBIuMYI0E13cURY3C5o6fT3YHA9eX+PQBgYUgefVo5HElQwa4LyOdWNy4bRUJ8HxFTCA5yUjGp7HMMNW5Z2itiugNw/VAUyKWuSBltjdKOUogWh0OmJ0SsTPz11mjNQUtlpYUKaCpmXsDhD3oz3P6fLuD/FgiEgYR6wrc3Iij8oxA4VieRK6RYGElyrZ9hL2lMSLY9524C+wzQ6XRoo5mUqggf6ej7wGMGy/g5H/8GFjrkRxmNQhyMfZ2WV1nKIXE8ofMJKbk4esg6t4cKCsoPAufLZZqyesDWKIsWEaH+PtINVpcCR9XCirFPvdeqOFh/ihI/Gcpwf5iTY=
deploy:
  provider: npm
  email: albertofdzm@gmail.com
  api_key:
    secure: ac5lpljvg+XEC6xvOzkh7I5PqlQmZ0+XHz/wiwqwfcCCVQ8NM0r5pr+bOr49t9mb18Q/iEAHjhU3LUp2g7FnY8WzrmmYzamVAf9DKLtAmtV8+XVj1w+I0Ha+ZabfpGFmZwpvsv6OvwLMhuKiIOQNlkF6QDv7AEvUnM26BGvy/OCJ+FxfLE006mnr79nqedHivdxGixD54Bm+W0sq2NTOvBoQ5GdxIxqO6QRXJbgD6fHiDcQr5ETVkYfVLndu0xpAS2hULxZw4f7cNBZEEl0LQgZ9AIt/6161hYceohL4jWaSyKxWayA0Lr6Cvm/0Tq2uxQqxJceZZEXx+SI4Fu77Y/mvumz8BCYagDuznOFYSR3wI1Ab+uFH05QrNNrCtiJApcnl+nsqI7qc0PDiA6cPUJQ0n35fzq0Kv9udJ5VuuyJKOfb85p/vDcKzgSp2NaLnTImZYJe8FJohtg9fegavhtUTLWoSCSBhchFZQoxArhtByA+nqQBKSjGiZ4fsHKEO6oC/y8nIYDkuLHxhR0d06qwSjGIQZfRYl7rnc0z7SPW7pVQ9L+K1ZGsqI9OQRvYtXL+RJ4lqGrWFd3kHoEfadXm69OnuKTuyfaSf61q9jNp4IetQBqwtuHqGxyKipfVYYCLDTVShJSdliiZLUnKdut9fdpz2wb5Ome4+TGhHJyQ=
